
<?php 
echo Phalcon\Tag::form('client/edit/'.$Client->getId());
?>
<div class="card">
	<div class="card-header">
		<h5><span class="fa fa-pen text-success"> </span> Client Edit</h5>
	</div>
	<div class="card-body">
		<?php echo $this->flash->output(); ?>
		<div class="row">
			<div class="col-12 col-lg-6">
				<div class="input-group mb-3">
				  <span class="input-group-text" id="inputGroup-sizing-default">Name *</span>
				 <?php echo $this->tag->textField(['name' , "value"=>$Client->getName(),"class"=>"form-control","required"=>1]); ?>
				</div>
			</div>
			<div class="col-12 col-lg-6">
				<div class="input-group mb-3">
				  <span class="input-group-text" id="inputGroup-sizing-default">Country</span>
				 <?php echo $this->tag->textField(['country' , "value"=>$Client->getCountry(),"class"=>"form-control"]); ?>
				</div>
					<div  class="form-text text-muted d-sm-none d-md-block">Please use ISO-3166-1 ALPHA-2 code - <a href="https://laendercode.net/en/2-letter-list.html" target="_blank" class="text-info"><span class="fa fa-link"></span> Liste complète</a></div>
			</div>
		</div>
		<div class="row mt-3">
			<div class="col-12">
				<div class="input-group mb-3">
				  <span class="input-group-text" id="inputGroup-sizing-default">Address</span>
				 <?php echo $this->tag->textArea(['address' , "value"=>$Client->getAddress(),"class"=>"form-control","rows"=>5]); ?>
				</div>
			</div>
			
		</div>
		
		<div class="row mt-3">
			<div class="col text-center">
				<?php 
					echo $this->tag->submitButton([
						"Update client informations",
						"class" => "btn btn-info text-white"
					])
				?>
			</div>
		</div>
	</div>
</div>
<?php 
echo Phalcon\Tag::endForm();
?>

<div class="card">
	<div class="card-header">
		<h5><span class="fa fa-box text-success"> </span> Product Shop</h5>
	</div>
	<div class="card-body">
		<table class="table table-bordered table-hover">
			<thead class="thead-light">
				<tr class="bg-info text-white">
					
					<th>ID</th>
					<th>Name</th>
					<th>Price ($)</th>
					<th>Tax (%)</th>
					<th>Price with Tax ($)</th>
					<th>Available</th>
					<th>NB Wanted</th>
					<th>-</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<td colspan="3">Products available : <?php echo $Products->count(); ?></td>
				</tr>
			</tfoot>
			<tbody>
			<?php 
			if ($Products->count() > 0) {
			?>
			<?php foreach ($Products as $product) { ?>
			<?php 
				echo Phalcon\Tag::form('client/buy/'.$Client->getId());
				echo Phalcon\Tag::hiddenField(['product_id',"value"=>$product->getId()]);
			?>
				<tr>
					
					<td><?php echo $product->getId(); ?></td>
					<td><?php echo $product->getName(); ?></td>
					<td><?php echo $product->convertPriceOutput(); ?></td>
					<td><?php echo $product->convertTaxOutput(); ?></td>
					<td><?php echo number_format($product->getPriceWithTax(),2,'.',''); ?></td>
					<td><?php echo $product->getStock(); ?></td>
					<td><?php echo $this->tag->numericField(['quantity',"value"=>0,"step" => 1,"min"=>0,"max"=>$product->getStock()]); ?></td>
					<td><?php 
					echo $this->tag->submitButton([
						"Buy !",
						"class" => "btn btn-info text-white"
					])
				?></td>
				</tr>
			<?php 
				echo Phalcon\Tag::endForm();
			?>
			<?php } ?>
			
		<?php }else{ ?>
				<tr>
					<td class="text-center" colspan="5"><i>No results</i></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>