
<?php 
echo Phalcon\Tag::form('transactionClient/add');
?>
<div class="card">
	<div class="card-header">
		<h5><span class="fa fa-pen text-success"> </span> Add Client Transaction</h5>
	</div>
	<div class="card-body">
		<?php echo $this->flash->output(); ?>
		<div class="row">
			<div class="col-12 col-lg-6">
				<div class="input-group mb-3">
				  <span class="input-group-text" id="inputGroup-sizing-default">(Seller) Company *</span>
				 <?php echo $companyDropdown; ?>
				</div>
			</div>
			<div class="col-12 col-lg-6">
				<div class="input-group mb-3">
				  <span class="input-group-text" id="inputGroup-sizing-default">(Buyer) Client *</span>
				 <?php echo $clientDropdown; ?>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-12 col-lg-6">
				<div class="input-group mb-3">
				  <span class="input-group-text" id="inputGroup-sizing-default">Product *</span>
				 <?php echo $productDropdown; ?>
				</div>
			</div>
			<div class="col-12 col-lg-6">
				<div class="input-group mb-3">
				  <span class="input-group-text" id="inputGroup-sizing-default">Quantity *</span>
				 <?php echo $this->tag->numericField(['quantity',"value"=>$Transaction->getQuantity(), "class"=>"form-control", "min"=>1 , "step"=>1 ,"required"=>1]); ?>
				</div>
			</div>
		</div>
		
		<div class="row mt-3">
			<div class="col text-center">
				<?php 
					echo $this->tag->submitButton([
						"Create transaction",
						"class" => "btn btn-info text-white"
					])
				?>
			</div>
		</div>
	</div>
</div>
<?php 
echo Phalcon\Tag::endForm();
?>