<div class="alert alert-warning" role="alert">
	  <h4 class="alert-heading">This page under construction</h4>
	  <p>
			It's not ready yet. Come back later for more feature !
	  </p>
	</div>
<div class="card">
	<div class="card-header">
		<h5>Transactions between Companies and Clients</h5>
	</div>
	
	<div class="card-body">
		<?php echo $this->flash->output(); ?>
			<table class="table table-bordered table-hover">
				<thead class="thead-light">
					<tr class="bg-info text-white">
						<?php if(!$Administrator->getReadOnly()){ ?>
							<th style="width:2%" class="text-center"><?php echo $this->tag->LinkTo('transactionClient/add','<span title="Add a transaction" class="fa fa-plus text-success"> </span>'); ?></th>
						<?php } ?>
						<th>ID</th>
						<th>Client</th>
						<th>Company</th>
						<th>Product</th>
						<th>Qty</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td colspan="3">Transactions quantity: <?php echo $Transactions->count(); ?></td>
					</tr>
				</tfoot>
				<tbody>
				<?php 
				if ($Transactions->count() > 0) {
				?>
				<?php foreach ($Transactions as $transaction) { ?>
					<tr>
						<?php if(!$Administrator->getReadOnly()){ ?><td nowrap>
							<?php echo $this->tag->LinkTo(['#','<span title="Delete a transaction" class="fa fa-trash text-danger"> </span>','class' => 'action_delete']); ?>
							&nbsp;&nbsp;
							<?php echo $this->tag->LinkTo('#','<span title="Edit a transaction" class="fa fa-pen text-success"> </span>'); ?>
						</td><?php } ?>
						
						<td><?php echo $transaction->Client->getName(); ?></td>
						<td><?php echo $transaction->Company->getName(); ?></td>
						<td><?php echo $transaction->Product->getName(); ?></td>
						<td><?php echo $transaction->Product->convertPriceOutput(); ?></td>
						<td><?php echo $transaction->getQuantity(); ?></td>
					</tr>
				<?php } ?>
				
			<?php }else{ ?>
					<tr>
						<td class="text-center" colspan="5"><i>No results</i></td>
					</tr>
				<?php } ?>
				</tbody>
			</table>
	</div>
</div>